onEvent('item.registry', itms => {
	itms.create('fbmodium_helmet' ).type('helmet').tier('fbmodium').displayName('Fbmodium Helmet')
	itms.create('fbmodium_chestplate' ).type('chestplate').tier('fbmodium').displayName('Fbmodium Chestplate')
	itms.create('fbmodium_leggings' ).type('leggings').tier('fbmodium').displayName('Fbmodium Leggings')
	itms.create('fbmodium_boots' ).type('boots').tier('fbmodium').displayName('Fbmodium Boots')
	itms.create('nether_infused_helmet' ).type('helmet').tier('nether_infused_fbmodium').displayName('Nether Infused Fbmodium Helmet')
	itms.create('nether_infused_chestplate' ).type('chestplate').tier('nether_infused_fbmodium').displayName('Nether Infused Fbmodium Chestplate')
	itms.create('nether_infused_leggings' ).type('leggings').tier('nether_infused_fbmodium').displayName('Nether Infused Fbmodium Leggings')
	itms.create('nether_infused_boots' ).type('boots').tier('nether_infused_fbmodium').displayName('Nether Infused Fbmodium Boots')
	itms.create('end_infused_helmet' ).type('helmet').tier('end_infused_fbmodium').displayName('End Infused Fbmodium Helmet')
	itms.create('end_infused_chestplate' ).type('chestplate').tier('end_infused_fbmodium').displayName('End Infused Fbmodium Chestplate')
	itms.create('end_infused_leggings' ).type('leggings').tier('end_infused_fbmodium').displayName('End Infused Fbmodium Leggings')
	itms.create('end_infused_boots' ).type('boots').tier('end_infused_fbmodium').displayName('End Infused Fbmodium Boots')
	itms.create('ultimate_infused_helmet' ).type('helmet').tier('ultimate_infused_fbmodium').displayName('Ultimate Infused Fbmodium Helmet')
	itms.create('ultimate_infused_chestplate' ).type('chestplate').tier('ultimate_infused_fbmodium').displayName('Ultimate Infused Fbmodium Chestplate')
	itms.create('ultimate_infused_leggings' ).type('leggings').tier('ultimate_infused_fbmodium').displayName('Ultimate Infused Fbmodium Leggings')
	itms.create('ultimate_infused_boots' ).type('boots').tier('ultimate_infused_fbmodium').displayName('Ultimate Infused Fbmodium Boots')
})