// Tier 4
<recipetype:immersiveengineering:cloche>.addRecipe("prosper_sh_1seed", <item:mysticalagriculture:gold_seeds>, <item:mysticalagriculture:imperium_farmland>, 100, [<item:minecraft:gold_ingot> * 4, <item:mysticalagriculture:gold_seeds>], <blockstate:mysticalagriculture:redstone_crop:age=0>.block, "crop");
<recipetype:immersiveengineering:cloche>.addRecipe("prosper_sh_2seed", <item:mysticalagriculture:lapis_lazuli_seeds>, <item:mysticalagriculture:imperium_farmland>, 100, [<item:minecraft:lapis_lazuli> * 4, <item:mysticalagriculture:lapis_lazuli_seeds>], <blockstate:mysticalagriculture:redstone_crop:age=0>.block, "crop");
<recipetype:immersiveengineering:cloche>.addRecipe("prosper_sh_3seed", <item:mysticalagriculture:end_seeds>, <item:mysticalagriculture:imperium_farmland>, 100, [<item:mysticalagriculture:end_essence>* 4, <item:mysticalagriculture:end_seeds>], <blockstate:mysticalagriculture:redstone_crop:age=0>.block, "crop");
<recipetype:immersiveengineering:cloche>.addRecipe("prosper_sh_4seed", <item:mysticalagriculture:experience_seeds>, <item:mysticalagriculture:imperium_farmland>, 100, [<item:minecraft:experience_bottle> * 4, <item:mysticalagriculture:experience_seeds>], <blockstate:mysticalagriculture:redstone_crop:age=0>.block, "crop");
<recipetype:immersiveengineering:cloche>.addRecipe("prosper_sh_5seed", <item:mysticalagriculture:blaze_seeds>, <item:mysticalagriculture:imperium_farmland>, 100, [<item:minecraft:blaze_rod> * 4, <item:mysticalagriculture:blaze_seeds>], <blockstate:mysticalagriculture:redstone_crop:age=0>.block, "crop");
<recipetype:immersiveengineering:cloche>.addRecipe("prosper_sh_6seed", <item:mysticalagriculture:ghast_seeds>, <item:mysticalagriculture:imperium_farmland>, 100, [<item:minecraft:ghast_tear> * 4, <item:mysticalagriculture:ghast_seeds>], <blockstate:mysticalagriculture:redstone_crop:age=0>.block, "crop");
<recipetype:immersiveengineering:cloche>.addRecipe("prosper_sh_7seed", <item:mysticalagriculture:enderman_seeds>, <item:mysticalagriculture:imperium_farmland>, 100, [<item:mysticalagriculture:enderman_essence> * 4, <item:mysticalagriculture:enderman_seeds>], <blockstate:mysticalagriculture:redstone_crop:age=0>.block, "crop");
<recipetype:immersiveengineering:cloche>.addRecipe("prosper_sh_8seed", <item:mysticalagriculture:steel_seeds>, <item:mysticalagriculture:imperium_farmland>, 100, [<item:mekanism:ingot_steel> * 4, <item:mysticalagriculture:steel_seeds>], <blockstate:mysticalagriculture:redstone_crop:age=0>.block, "crop");
<recipetype:immersiveengineering:cloche>.addRecipe("prosper_sh_9seed", <item:mysticalagriculture:nickel_seeds>, <item:mysticalagriculture:imperium_farmland>, 100, [<item:thermal:nickel_ingot> * 4, <item:mysticalagriculture:nickel_seeds>], <blockstate:mysticalagriculture:redstone_crop:age=0>.block, "crop");
<recipetype:immersiveengineering:cloche>.addRecipe("prosper_sh_10seed", <item:mysticalagriculture:constantan_seeds>, <item:mysticalagriculture:imperium_farmland>, 100, [<item:thermal:constantan_ingot> * 4, <item:mysticalagriculture:constantan_seeds>], <blockstate:mysticalagriculture:redstone_crop:age=0>.block, "crop");
<recipetype:immersiveengineering:cloche>.addRecipe("prosper_sh_11seed", <item:mysticalagriculture:electrum_seeds>, <item:mysticalagriculture:imperium_farmland>, 100, [<item:thermal:electrum_ingot> * 4, <item:mysticalagriculture:electrum_seeds>], <blockstate:mysticalagriculture:redstone_crop:age=0>.block, "crop");
<recipetype:immersiveengineering:cloche>.addRecipe("prosper_sh_12seed", <item:mysticalagriculture:invar_seeds>, <item:mysticalagriculture:imperium_farmland>, 100, [<item:thermal:invar_ingot> * 4, <item:mysticalagriculture:invar_seeds>], <blockstate:mysticalagriculture:redstone_crop:age=0>.block, "crop");
<recipetype:immersiveengineering:cloche>.addRecipe("prosper_sh_13seed", <item:mysticalagriculture:mithril_seeds>, <item:mysticalagriculture:imperium_farmland>, 100, [<item:mysticalagriculture:mithril_essence> * 4, <item:mysticalagriculture:mithril_seeds>], <blockstate:mysticalagriculture:redstone_crop:age=0>.block, "crop");
<recipetype:immersiveengineering:cloche>.addRecipe("prosper_sh_133eed", <item:mysticalagriculture:tungsten_seeds>, <item:mysticalagriculture:imperium_farmland>, 100, [<item:moremekanismprocessing:tungsten_ingot> * 4, <item:mysticalagriculture:tungsten_seeds>], <blockstate:mysticalagriculture:redstone_crop:age=0>.block, "crop");
<recipetype:immersiveengineering:cloche>.addRecipe("prosper_sh_15seed", <item:mysticalagriculture:titanium_seeds>, <item:mysticalagriculture:imperium_farmland>, 100, [<item:moremekanismprocessing:titanium_ingot> * 4, <item:mysticalagriculture:titanium_seeds>], <blockstate:mysticalagriculture:redstone_crop:age=0>.block, "crop");
<recipetype:immersiveengineering:cloche>.addRecipe("prosper_sh_16seed", <item:mysticalagriculture:uranium_seeds>, <item:mysticalagriculture:imperium_farmland>, 100, [<item:mekanism:ingot_uranium> * 4, <item:mysticalagriculture:uranium_seeds>], <blockstate:mysticalagriculture:redstone_crop:age=0>.block, "crop");
<recipetype:immersiveengineering:cloche>.addRecipe("prosper_sh_17seed", <item:mysticalagriculture:chrome_seeds>, <item:mysticalagriculture:imperium_farmland>, 100, [<item:mysticalagriculture:chrome_essence> * 4, <item:mysticalagriculture:chrome_seeds>], <blockstate:mysticalagriculture:redstone_crop:age=0>.block, "crop");
<recipetype:immersiveengineering:cloche>.addRecipe("prosper_sh_18seed", <item:mysticalagriculture:ruby_seeds>, <item:mysticalagriculture:imperium_farmland>, 100, [<item:moremekanismprocessing:gem_ruby> * 4, <item:mysticalagriculture:ruby_seeds>], <blockstate:mysticalagriculture:redstone_crop:age=0>.block, "crop");
<recipetype:immersiveengineering:cloche>.addRecipe("prosper_sh_19seed", <item:mysticalagriculture:sapphire_seeds>, <item:mysticalagriculture:imperium_farmland>, 100, [<item:moremekanismprocessing:gem_sapphire> * 4, <item:mysticalagriculture:sapphire_seeds>], <blockstate:mysticalagriculture:redstone_crop:age=0>.block, "crop");
<recipetype:immersiveengineering:cloche>.addRecipe("prosper_sh_20seed", <item:mysticalagriculture:signalum_seeds>, <item:mysticalagriculture:imperium_farmland>, 100, [<item:thermal:signalum_ingot> * 4, <item:mysticalagriculture:signalum_seeds>], <blockstate:mysticalagriculture:redstone_crop:age=0>.block, "crop");
<recipetype:immersiveengineering:cloche>.addRecipe("prosper_sh_21seed", <item:mysticalagriculture:lumium_seeds>, <item:mysticalagriculture:imperium_farmland>, 100, [<item:thermal:lumium_ingot> * 4, <item:mysticalagriculture:lumium_seeds>], <blockstate:mysticalagriculture:redstone_crop:age=0>.block, "crop");
<recipetype:immersiveengineering:cloche>.addRecipe("prosper_sh_22seed", <item:mysticalagriculture:osmium_seeds>, <item:mysticalagriculture:imperium_farmland>, 100, [<item:mekanism:ingot_osmium> * 4, <item:mysticalagriculture:osmium_seeds>], <blockstate:mysticalagriculture:redstone_crop:age=0>.block, "crop");
<recipetype:immersiveengineering:cloche>.addRecipe("prosper_sh_23seed", <item:mysticalagriculture:fluorite_seeds>, <item:mysticalagriculture:imperium_farmland>, 100, [<item:mekanism:fluorite_gem> * 4, <item:mysticalagriculture:fluorite_seeds>], <blockstate:mysticalagriculture:redstone_crop:age=0>.block, "crop");
<recipetype:immersiveengineering:cloche>.addRecipe("prosper_sh_24seed", <item:mysticalagriculture:refined_glowstone_seeds>, <item:mysticalagriculture:imperium_farmland>, 100, [<item:mekanism:ingot_refined_glowstone> * 4, <item:mysticalagriculture:refined_glowstone_seeds>], <blockstate:mysticalagriculture:redstone_crop:age=0>.block, "crop");
<recipetype:immersiveengineering:cloche>.addRecipe("prosper_sh_25seed", <item:mysticalagriculture:refined_obsidian_seeds>, <item:mysticalagriculture:imperium_farmland>, 100, [<item:mekanism:dust_refined_obsidian> * 4, <item:mysticalagriculture:refined_obsidian_seeds>], <blockstate:mysticalagriculture:redstone_crop:age=0>.block, "crop");
<recipetype:immersiveengineering:cloche>.addRecipe("prosper_sh_26seed", <item:mysticalagriculture:knightmetal_seeds>, <item:mysticalagriculture:imperium_farmland>, 100, [<item:twilightforest:knightmetal_ingot> * 4, <item:mysticalagriculture:knightmetal_seeds>], <blockstate:mysticalagriculture:redstone_crop:age=0>.block, "crop");
<recipetype:immersiveengineering:cloche>.addRecipe("prosper_sh_27seed", <item:mysticalagriculture:fiery_ingot_seeds>, <item:mysticalagriculture:imperium_farmland>, 100, [<item:twilightforest:fiery_ingot> * 4, <item:mysticalagriculture:fiery_ingot_seeds>], <blockstate:mysticalagriculture:redstone_crop:age=0>.block, "crop");
<recipetype:immersiveengineering:cloche>.addRecipe("prosper_sh_28seed", <item:mysticalagriculture:fluix_seeds>, <item:mysticalagriculture:imperium_farmland>, 100, [<item:appliedenergistics2:fluix_crystal> * 4, <item:mysticalagriculture:fluix_seeds>], <blockstate:mysticalagriculture:redstone_crop:age=0>.block, "crop");
<recipetype:immersiveengineering:cloche>.addRecipe("prosper_sh_29seed", <item:mysticalagriculture:energized_steel_seeds>, <item:mysticalagriculture:imperium_farmland>, 100, [<item:powah:steel_energized> * 4, <item:mysticalagriculture:energized_steel_seeds>], <blockstate:mysticalagriculture:redstone_crop:age=0>.block, "crop");
<recipetype:immersiveengineering:cloche>.addRecipe("prosper_sh_30seed", <item:mysticalagriculture:blazing_crystal_seeds>, <item:mysticalagriculture:imperium_farmland>, 100, [<item:powah:crystal_blazing> * 4, <item:mysticalagriculture:blazing_crystal_seeds>], <blockstate:mysticalagriculture:redstone_crop:age=0>.block, "crop");

// Tier 5
<recipetype:immersiveengineering:cloche>.addRecipe("prosper_sh_seed1", <item:mysticalagriculture:diamond_seeds>, <item:mysticalagriculture:supremium_farmland>, 100, [<item:minecraft:diamond> * 5, <item:mysticalagriculture:diamond_seeds>], <blockstate:mysticalagriculture:redstone_crop:age=0>.block, "crop");
<recipetype:immersiveengineering:cloche>.addRecipe("prosper_sh_seed2", <item:mysticalagriculture:emerald_seeds>, <item:mysticalagriculture:supremium_farmland>, 100, [<item:minecraft:emerald> * 5, <item:mysticalagriculture:emerald_seeds>], <blockstate:mysticalagriculture:redstone_crop:age=0>.block, "crop");
<recipetype:immersiveengineering:cloche>.addRecipe("prosper_sh_seed3", <item:mysticalagriculture:netherite_seeds>, <item:mysticalagriculture:supremium_farmland>, 100, [<item:minecraft:netherite_ingot> * 5, <item:mysticalagriculture:netherite_seeds>], <blockstate:mysticalagriculture:redstone_crop:age=0>.block, "crop");
<recipetype:immersiveengineering:cloche>.addRecipe("prosper_sh_seed4", <item:mysticalagriculture:wither_skeleton_seeds>, <item:mysticalagriculture:supremium_farmland>, 100, [<item:minecraft:wither_skeleton_skull> * 5, <item:mysticalagriculture:wither_skeleton_seeds>], <blockstate:mysticalagriculture:redstone_crop:age=0>.block, "crop");
<recipetype:immersiveengineering:cloche>.addRecipe("prosper_sh_seed5", <item:mysticalagriculture:platinum_seeds>, <item:mysticalagriculture:supremium_farmland>, 100, [<item:moremekanismprocessing:platinum_ingot> * 5, <item:mysticalagriculture:platinum_seeds>], <blockstate:mysticalagriculture:redstone_crop:age=0>.block, "crop");
<recipetype:immersiveengineering:cloche>.addRecipe("prosper_sh_seed6", <item:mysticalagriculture:iridium_seeds>, <item:mysticalagriculture:supremium_farmland>, 100, [<item:moremekanismprocessing:iridium_ingot> * 5, <item:mysticalagriculture:iridium_seeds>], <blockstate:mysticalagriculture:redstone_crop:age=0>.block, "crop");
<recipetype:immersiveengineering:cloche>.addRecipe("prosper_sh_seed7", <item:mysticalagriculture:enderium_seeds>, <item:mysticalagriculture:supremium_farmland>, 100, [<item:thermal:enderium_ingot> * 5, <item:mysticalagriculture:enderium_seeds>], <blockstate:mysticalagriculture:redstone_crop:age=0>.block, "crop");
<recipetype:immersiveengineering:cloche>.addRecipe("prosper_sh_seed9", <item:mysticalagriculture:niotic_crystal_seeds>, <item:mysticalagriculture:supremium_farmland>, 100, [<item:powah:crystal_niotic> * 5, <item:mysticalagriculture:niotic_crystal_seeds>], <blockstate:mysticalagriculture:redstone_crop:age=0>.block, "crop");
<recipetype:immersiveengineering:cloche>.addRecipe("prosper_sh_seed10", <item:mysticalagriculture:spirited_crystal_seeds>, <item:mysticalagriculture:supremium_farmland>, 100, [<item:powah:crystal_spirited> * 5, <item:mysticalagriculture:spirited_crystal_seeds>], <blockstate:mysticalagriculture:redstone_crop:age=0>.block, "crop");
<recipetype:immersiveengineering:cloche>.addRecipe("prosper_sh_seed11", <item:mysticalagriculture:uraninite_seeds>, <item:mysticalagriculture:supremium_farmland>, 100, [<item:powah:uraninite_raw_poor> * 5, <item:mysticalagriculture:uraninite_seeds>], <blockstate:mysticalagriculture:redstone_crop:age=0>.block, "crop");

// Tier 6
<recipetype:immersiveengineering:cloche>.addRecipe("prosper_sh_seed-extra1", <item:mysticalagriculture:nether_star_seeds>, <item:mysticalagradditions:insanium_farmland>, 100, [<item:minecraft:nether_star> * 6, <item:mysticalagriculture:nether_star_seeds>], <blockstate:mysticalagriculture:redstone_crop:age=0>.block, "crop");
<recipetype:immersiveengineering:cloche>.addRecipe("prosper_sh_seed-extra2", <item:mysticalagriculture:dragon_egg_seeds>, <item:mysticalagradditions:insanium_farmland>, 100, [<item:mysticalagriculture:dragon_egg_essence> * 6, <item:mysticalagriculture:dragon_egg_seeds>], <blockstate:mysticalagriculture:redstone_crop:age=0>.block, "crop");
<recipetype:immersiveengineering:cloche>.addRecipe("prosper_sh_seed-extra4", <item:mysticalagriculture:nitro_crystal_seeds>, <item:mysticalagradditions:insanium_farmland>, 100, [<item:powah:crystal_nitro> * 6, <item:mysticalagriculture:nitro_crystal_seeds>], <blockstate:mysticalagriculture:redstone_crop:age=0>.block, "crop");
<recipetype:immersiveengineering:cloche>.addRecipe("prosper_sh_seed-extra5", <item:contenttweaker:goldrite_seeds>, <item:mysticalagradditions:insanium_farmland>, 100, [<item:upgradednetherite:gold_upgraded_netherite_ingot> * 6, <item:contenttweaker:goldrite_seeds>], <blockstate:mysticalagriculture:redstone_crop:age=0>.block, "crop");
<recipetype:immersiveengineering:cloche>.addRecipe("prosper_sh_seed-extra6", <item:contenttweaker:blazerite_seeds>, <item:mysticalagradditions:insanium_farmland>, 100, [<item:upgradednetherite:fire_upgraded_netherite_ingot> * 6, <item:contenttweaker:blazerite_seeds>], <blockstate:mysticalagriculture:redstone_crop:age=0>.block, "crop");
<recipetype:immersiveengineering:cloche>.addRecipe("prosper_sh_seed-extra7", <item:contenttweaker:enderite_seeds>, <item:mysticalagradditions:insanium_farmland>, 100, [<item:upgradednetherite:ender_upgraded_netherite_ingot> * 6, <item:contenttweaker:enderite_seeds>], <blockstate:mysticalagriculture:redstone_crop:age=0>.block, "crop");
<recipetype:immersiveengineering:cloche>.addRecipe("prosper_sh_seed-extra8", <item:contenttweaker:prismarite_seeds>, <item:mysticalagradditions:insanium_farmland>, 100, [<item:upgradednetherite:water_upgraded_netherite_ingot> * 6, <item:contenttweaker:prismarite_seeds>], <blockstate:mysticalagriculture:redstone_crop:age=0>.block, "crop");
<recipetype:immersiveengineering:cloche>.addRecipe("prosper_sh_seed-extra9", <item:contenttweaker:witherite_seeds>, <item:mysticalagradditions:insanium_farmland>, 100, [<item:upgradednetherite:wither_upgraded_netherite_ingot> * 6, <item:contenttweaker:witherite_seeds>], <blockstate:mysticalagriculture:redstone_crop:age=0>.block, "crop");
<recipetype:immersiveengineering:cloche>.addRecipe("prosper_sh_seed-extra10", <item:contenttweaker:spiderite_seeds>, <item:mysticalagradditions:insanium_farmland>, 100, [<item:upgradednetherite:poison_upgraded_netherite_ingot> * 6, <item:contenttweaker:spiderite_seeds>], <blockstate:mysticalagriculture:redstone_crop:age=0>.block, "crop");
<recipetype:immersiveengineering:cloche>.addRecipe("prosper_sh_seed-extra11", <item:contenttweaker:phanterite_seeds>, <item:mysticalagradditions:insanium_farmland>, 100, [<item:upgradednetherite:phantom_upgraded_netherite_ingot> * 6, <item:contenttweaker:phanterite_seeds>], <blockstate:mysticalagriculture:redstone_crop:age=0>.block, "crop");
<recipetype:immersiveengineering:cloche>.addRecipe("prosper_sh_seed-extra12", <item:contenttweaker:featherite_seeds>, <item:mysticalagradditions:insanium_farmland>, 100, [<item:upgradednetherite:feather_upgraded_netherite_ingot> * 6, <item:contenttweaker:featherite_seeds>], <blockstate:mysticalagriculture:redstone_crop:age=0>.block, "crop");
<recipetype:immersiveengineering:cloche>.addRecipe("prosper_sh_seed-extra13", <item:contenttweaker:corrupterite_seeds>, <item:mysticalagradditions:insanium_farmland>, 100, [<item:upgradednetherite:corrupt_upgraded_netherite_ingot> * 6, <item:contenttweaker:corrupterite_seeds>], <blockstate:mysticalagriculture:redstone_crop:age=0>.block, "crop");

// Tier 7
