# thief's glove

mods.extendedcrafting.TableCrafting.addShaped("2c24e1ee-c951-438a-bbcb-c94a47ce62d6", 0, <item:theft:glove>, [
	[<item:extendedcrafting:luminessence>, <item:extendedcrafting:luminessence>, <item:extendedcrafting:luminessence>, <item:extendedcrafting:luminessence>, <item:extendedcrafting:luminessence>, <item:extendedcrafting:luminessence>, <item:extendedcrafting:luminessence>, <item:extendedcrafting:luminessence>, <item:extendedcrafting:luminessence>], 
	[<item:extendedcrafting:luminessence>, <item:extendedcrafting:luminessence>, <item:extendedcrafting:luminessence>, <item:extendedcrafting:luminessence>, <item:extendedcrafting:luminessence>, <item:extendedcrafting:luminessence>, <item:extendedcrafting:luminessence>, <item:extendedcrafting:luminessence>, <item:extendedcrafting:luminessence>], 
	[<item:extendedcrafting:luminessence>, <item:extendedcrafting:luminessence>, <item:mekanism:ingot_osmium>, <item:mekanism:ingot_tin>, <item:mekanism:ingot_uranium>, <item:mekanism:ingot_tin>, <item:mekanism:ingot_osmium>, <item:extendedcrafting:luminessence>, <item:extendedcrafting:luminessence>], 
	[<item:extendedcrafting:luminessence>, <item:extendedcrafting:luminessence>, <item:mekanism:ingot_lead>, <item:minecraft:netherite_ingot>, <item:minecraft:netherite_ingot>, <item:minecraft:netherite_ingot>, <item:mekanism:ingot_lead>, <item:extendedcrafting:luminessence>, <item:extendedcrafting:luminessence>], 
	[<item:extendedcrafting:luminessence>, <item:extendedcrafting:luminessence>, <item:mekanism:ingot_uranium>, <item:minecraft:netherite_ingot>, <item:minecraft:nether_star>, <item:minecraft:netherite_ingot>, <item:mekanism:ingot_uranium>, <item:extendedcrafting:luminessence>, <item:extendedcrafting:luminessence>], 
	[<item:extendedcrafting:luminessence>, <item:extendedcrafting:luminessence>, <item:mekanism:ingot_lead>, <item:minecraft:netherite_ingot>, <item:minecraft:netherite_ingot>, <item:minecraft:netherite_ingot>, <item:mekanism:ingot_lead>, <item:extendedcrafting:luminessence>, <item:extendedcrafting:luminessence>], 
	[<item:extendedcrafting:luminessence>, <item:extendedcrafting:luminessence>, <item:mekanism:ingot_osmium>, <item:mekanism:ingot_tin>, <item:mekanism:ingot_uranium>, <item:mekanism:ingot_tin>, <item:mekanism:ingot_osmium>, <item:extendedcrafting:luminessence>, <item:extendedcrafting:luminessence>], 
	[<item:extendedcrafting:luminessence>, <item:extendedcrafting:luminessence>, <item:extendedcrafting:luminessence>, <item:extendedcrafting:luminessence>, <item:extendedcrafting:luminessence>, <item:extendedcrafting:luminessence>, <item:extendedcrafting:luminessence>, <item:extendedcrafting:luminessence>, <item:extendedcrafting:luminessence>], 
	[<item:extendedcrafting:luminessence>, <item:extendedcrafting:luminessence>, <item:extendedcrafting:luminessence>, <item:extendedcrafting:luminessence>, <item:extendedcrafting:luminessence>, <item:extendedcrafting:luminessence>, <item:extendedcrafting:luminessence>, <item:extendedcrafting:luminessence>, <item:extendedcrafting:luminessence>]
]);
