

onEvent('item.tags', event => {

	event.add('forge:ingots/draconium', 'kubejs:draconium_ingot')
    event.add('forge:ingots/draconium_awakened', 'kubejs:awakened_draconium_ingot')
    event.add('forge:ingots/copper', 'kubejs:copper_ingot')
    event.add('forge:ingots/bronze', 'kubejs:bronze_ingot')
    event.add('forge:ingots/steel', 'kubejs:steel_ingot')
    event.add('forge:ingots/dark_steel', 'kubejs:dark_steel_ingot')
    event.add('forge:ingots/tin', 'kubejs:tin_ingot')
    event.add('forge:ingots/nickel', 'kubejs:nickel_ingot')
    event.add('forge:ingots/constantan', 'kubejs:constantan_ingot')
    event.add('forge:ingots/lead', 'kubejs:lead_ingot')
    event.add('forge:ingots/silver', 'kubejs:silver_ingot')
    event.add('forge:ingots/electrum', 'kubejs:electrum_ingot')
    event.add('forge:ingots/uranium', 'kubejs:uranium_ingot')
    event.add('forge:ingots/fbmodium', 'kubejs:fbmodium_ingot')
    event.add('forge:ingots/nether_infused_fbmodium', 'kubejs:nether_infused_fbmodium_ingot')
    event.add('forge:ingots/end_infused_fbmodium', 'kubejs:end_infused_fbmodium_ingot')
    event.add('forge:ingots/ultimate_infused_fbmodium', 'kubejs:ultimate_infused_fbmodium_ingot')
    event.add('forge:ingots/blue_iron', 'kubejs:blue_iron_ingot')
    event.add('forge:ingots/bluestone', 'kubejs:bluestone_ingot')
    event.add('forge:ingots/light_bluestone', 'kubejs:light_bluestone_ingot')
    event.add('forge:ingots/greenstone', 'kubejs:greenstone_ingot')
    event.add('forge:ingots/osmium', 'kubejs:osmium_ingot')
    event.add('forge:ingots/aluminium', 'kubejs:aluminium_ingot')
    event.add('forge:ingots/aluminum', 'kubejs:aluminium_ingot')

})