

onEvent('block.tags', event => {

	event.add('forge:ores/coal', 'kubejs:nether_coal_ore')
    event.add('forge:ores/coal', 'kubejs:end_coal_ore')
    event.add('forge:ores/copper', 'kubejs:nether_copper_ore')
    event.add('forge:ores/copper', 'kubejs:end_copper_ore')
    event.add('forge:ores/diamond', 'kubejs:nether_diamond_ore')
    event.add('forge:ores/diamond', 'kubejs:end_diamond_ore')
    event.add('forge:ores/iron', 'kubejs:nether_iron_ore')
    event.add('forge:ores/iron', 'kubejs:end_iron_ore')
    event.add('forge:ores/lapis', 'kubejs:nether_lapis_ore')
    event.add('forge:ores/lapis', 'kubejs:end_lapis_ore')
    event.add('forge:ores/emerald', 'kubejs:nether_emerald_ore')
    event.add('forge:ores/emerald', 'kubejs:end_emerald_ore')
    event.add('forge:ores/lead', 'kubejs:nether_lead_ore')
    event.add('forge:ores/lead', 'kubejs:end_lead_ore')
    event.add('forge:ores/osmium', 'kubejs:nether_osmium_ore')
    event.add('forge:ores/osmium', 'kubejs:end_osmium_ore')
    event.add('forge:ores/redstone', 'kubejs:nether_redstone_ore')
    event.add('forge:ores/redstone', 'kubejs:end_redstone_ore')
    event.add('forge:ores/tin', 'kubejs:nether_tin_ore')
    event.add('forge:ores/tin', 'kubejs:end_tin_ore')
    event.add('forge:ores/bluestone', 'kubejs:bluestone_ore')
    event.add('forge:ores/light_bluestone', 'kubejs:light_bluestone_ore')
    event.add('forge:ores/greenstone', 'kubejs:greenstone_ore')
    event.add('forge:ores/uranium', 'kubejs:nether_uranium_ore')
    event.add('forge:ores/uranium', 'kubejs:end_uranium_ore')
    event.add('forge:ores/cobalt', 'kubejs:cobalt_ore')
    event.add('forge:ores/ruby', 'kubejs:ruby_ore')
    event.add('forge:ores/sapphire', 'kubejs:sapphire_ore')



    event.add('forge:ores', 'kubejs:nether_coal_ore')
    event.add('forge:ores', 'kubejs:end_coal_ore')
    event.add('forge:ores', 'kubejs:nether_copper_ore')
    event.add('forge:ores', 'kubejs:end_copper_ore')
    event.add('forge:ores', 'kubejs:nether_diamond_ore')
    event.add('forge:ores', 'kubejs:end_diamond_ore')
    event.add('forge:ores', 'kubejs:nether_iron_ore')
    event.add('forge:ores', 'kubejs:end_iron_ore')
    event.add('forge:ores', 'kubejs:nether_lapis_ore')
    event.add('forge:ores', 'kubejs:end_lapis_ore')
    event.add('forge:ores', 'kubejs:nether_emerald_ore')
    event.add('forge:ores', 'kubejs:end_emerald_ore')
    event.add('forge:ores', 'kubejs:nether_lead_ore')
    event.add('forge:ores', 'kubejs:end_lead_ore')
    event.add('forge:ores', 'kubejs:nether_osmium_ore')
    event.add('forge:ores', 'kubejs:end_osmium_ore')
    event.add('forge:ores', 'kubejs:nether_redstone_ore')
    event.add('forge:ores', 'kubejs:end_redstone_ore')
    event.add('forge:ores', 'kubejs:nether_tin_ore')
    event.add('forge:ores', 'kubejs:end_tin_ore')
    event.add('forge:ores', 'kubejs:bluestone_ore')
    event.add('forge:ores', 'kubejs:light_bluestone_ore')
    event.add('forge:ores', 'kubejs:greenstone_ore')
    event.add('forge:ores', 'kubejs:nether_uranium_ore')
    event.add('forge:ores', 'kubejs:end_uranium_ore')
    event.add('forge:ores', 'kubejs:cobalt_ore')
    event.add('forge:ores', 'kubejs:ruby_ore')
    event.add('forge:ores', 'kubejs:sapphire_ore')
})