

onEvent('item.tags', event => {

	event.add('forge:rods/draconium', 'kubejs:draconium_rod')
    event.add('forge:rods/draconium_awakened', 'kubejs:awakened_draconium_rod')
    event.add('forge:rods/copper', 'kubejs:copper_rod')
    event.add('forge:rods/bronze', 'kubejs:bronze_rod')
    event.add('forge:rods/steel', 'kubejs:steel_rod')
    event.add('forge:rods/dark_steel', 'kubejs:dark_steel_rod')
    event.add('forge:rods/tin', 'kubejs:tin_rod')
    event.add('forge:rods/nickel', 'kubejs:nickel_rod')
    event.add('forge:rods/constantan', 'kubejs:constantan_rod')
    event.add('forge:rods/lead', 'kubejs:lead_rod')
    event.add('forge:rods/silver', 'kubejs:silver_rod')
    event.add('forge:rods/electrum', 'kubejs:electrum_rod')
    event.add('forge:rods/uranium', 'kubejs:uranium_rod')
    event.add('forge:rods/fbmodium', 'kubejs:fbmodium_rod')
    event.add('forge:rods/nether_infused_fbmodium', 'kubejs:nether_infused_fbmodium_rod')
    event.add('forge:rods/end_infused_fbmodium', 'kubejs:end_infused_fbmodium_rod')
    event.add('forge:rods/ultimate_infused_fbmodium', 'kubejs:ultimate_infused_fbmodium_rod')
    event.add('forge:rods/blue_iron', 'kubejs:blue_iron_rod')
    event.add('forge:rods/bluestone', 'kubejs:bluestone_rod')
    event.add('forge:rods/light_bluestone', 'kubejs:light_bluestone_rod')
    event.add('forge:rods/greenstone', 'kubejs:greenstone_rod')
    event.add('forge:rods/osmium', 'kubejs:osmium_rod')
    event.add('forge:rods/aluminium', 'kubejs:aluminium_rod')
    event.add('forge:rods/aluminum', 'kubejs:aluminium_rod')

})